name: blobinator
description: Tools and HTTP service for temporary binary blob storage.
version: 0.1.2
homepage: https://github.com/agilord/blobinator

executables:
  blobinator:
topics:
  - binary
  - server
  - tool

environment:
  sdk: '^3.8.0'

dependencies:
  args: ^2.6.0
  crypto: ^3.0.6
  http: ^1.2.2
  json_annotation: ^4.9.0
  path: ^1.9.1
  shelf: ^1.4.1
  shelf_router: ^1.1.4

dev_dependencies:
  build_runner: ^2.4.12
  json_serializable: ^6.8.0
  lints: ^5.1.1
  test: ^1.25.14
