name: blobinator
description: Tools and HTTP service for temporary binary blob storage.
version: 0.2.0
homepage: https://github.com/agilord/blobinator

executables:
  blobinator:
topics:
  - binary
  - server
  - tool

environment:
  sdk: '^3.8.0'

dependencies:
  args: ^2.6.0
  http: ^1.2.2
  path: ^1.9.1
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  sqlite3: ^2.4.6
  mime: ^2.0.0
dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.14
